### ISSUE TITLE
Marking locations as unavailable due to reasons apart from power being out

### ISSUE THREAD

**Issue by Era360** [fredygerman/umeme-upo#20]
People's devices can be offline for reasons other than power being out. For example, a device may be offline because it is being repaired or because the WIFI bundle is not paid yet. It would be useful to be able to mark a location as unavailable for reasons other than power being out.

**Comment by fredygerman** [comment]
For now, this can be done on the supabase dashboard by changing the field is_available to false, on the location entry.

And on the frontend that location will be marked as unavailable and the option will be disabled.
